name: translation_lib
description: Pacote com translation lib.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  perfil:
    git:
      url: https://github.com/JuliaMStahl/perfil.git
      ref: master
  dashboard:
    git:
      url: https://github.com/JuliaMStahl/dashboard.git
      ref: main
  acesso:
    git:
      url: https://github.com/JuliaMStahl/acesso.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
